name: Perl CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.40.1"
      - name: Install dependencies
        run: cpanm --installdeps .
      - name: Run tests
        run: prove -l t
